Repository JCS-Computer-Science/project-module-1-project-flip, pull requests merged in 2021-12, with the labels that each got.

#17 Staging
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement, critical

#19 Start github pages
  .github/workflows/dependabot.yml
  .github/workflows/labeler.yml
  Docs/Installation and getting started.md
  Vue/project-flip/README.md
Labels: In progress

#28 update new deplo branch
  .github/workflows/dependabot.yml
  .github/workflows/labeler.yml
  Docs/Installation and getting started.md
  Vue/project-flip/README.md
  Vue/project-flip/vue.config.js
Labels: In progress

#32 update with latest
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/dependabot.yml
  .github/workflows/spellcheck.yaml
  Docs/README.md
Labels: enhancement, In progress

#33 Update with latest
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/labeler.yml
  .github/workflows/spellcheck.yaml
  Docs/Installation and getting started.md
  Docs/README.md
  Vue/project-flip/README.md
  Vue/project-flip/vue.config.js
Labels: documentation, enhancement, critical, In progress, needs review

#39 Changed branch where dependency updates happen
  .github/dependabot.yml
Labels: critical, In progress, dependencies

#44 Update staging's dependency's -- needs to be checked
  Vue/project-flip/package-lock.json
  Vue/project-flip/package.json
Labels: critical, in progress, needs review, dependencies

#47 update Dev
  Vue/project-flip/package-lock.json
  Vue/project-flip/package.json
Labels: in progress, dependencies

#52 update dev dependency's with current
  Vue/project-flip/package-lock.json
  Vue/project-flip/package.json
Labels: Done, dependencies

#64 Install and configure tailwind CSS
  .vscode/extensions.json
  Vue/project-flip/.eslintrc.js
  Vue/project-flip/babel.config.js
  Vue/project-flip/jest.config.js
  Vue/project-flip/package-lock.json
  Vue/project-flip/package.json
  Vue/project-flip/postcss.config.js
  Vue/project-flip/src/App.vue
  Vue/project-flip/src/assets/tailwind.css
  Vue/project-flip/src/components/HelloWorld.vue
  Vue/project-flip/src/index.css
  Vue/project-flip/src/main.js
  Vue/project-flip/src/registerServiceWorker.js
  Vue/project-flip/src/store/index.js
  Vue/project-flip/src/views/About.vue
  Vue/project-flip/src/views/Build.vue
  Vue/project-flip/src/views/Contact.vue
  Vue/project-flip/src/views/Home.vue
  Vue/project-flip/src/views/Login.vue
  Vue/project-flip/src/views/Product_page_test.vue
  Vue/project-flip/src/views/Shop.vue
  Vue/project-flip/src/views/Signup.vue
  Vue/project-flip/tailwind.config.js
  Vue/project-flip/tests/e2e/.eslintrc.js
  Vue/project-flip/tests/e2e/custom-assertions/elementCount.js
  Vue/project-flip/tests/e2e/custom-commands/customExecute.js
  Vue/project-flip/tests/e2e/custom-commands/openHomepage.js
  Vue/project-flip/tests/e2e/custom-commands/openHomepageClass.js
  Vue/project-flip/tests/e2e/globals.js
  Vue/project-flip/tests/e2e/page-objects/homepage.js
  Vue/project-flip/tests/e2e/specs/test-with-pageobjects.js
  Vue/project-flip/tests/e2e/specs/test.js
  Vue/project-flip/tests/unit/example.spec.js
Labels: enhancement, help wanted, critical, in progress, dependencies
